name: Run test

on:
  push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox build tox-gh-actions
      - name: Test with tox
        run: tox
    strategy:
      matrix:
        python-version: ['3.10', 3.11, 3.12, 3.13]
