name: Run test

on:
  push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: docker.pkg.github.com/agriconnect/docker-poetry/poetry:1.0
    steps:
      - uses: actions/checkout@master
      - run: poetry install --no-root -v
      - run: poetry run pytest
