name: Run test

on:
  push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: Gr1N/setup-poetry@v4
        with:
          poetry-version: 1.1.4
      - uses: fedora-python/tox-github-action
        with:
          tox_env: ${{ matrix.tox_env }}
      strategy:
        matrix:
          tox_env: [py36, py37, py38]
